INSERT INTO Employees (Name, Role, Branch_ID) VALUES
('James Anderson', 'Manager', 1),
('Sarah Mitchell', 'Assistant Manager', 1),
('Michael Chen', 'Teller', 1),
('Emily Rodriguez', 'Teller', 1),
('David Thompson', 'Loan Officer', 1),
('Jessica Brown', 'Customer Support', 1),
('Robert Williams', 'Security Officer', 1),
('Amanda Davis', 'Accountant', 1),
('Christopher Lee', 'IT Support', 1),
('Michelle Martinez', 'HR Manager', 1),
('Daniel Garcia', 'Manager', 2),
('Laura Wilson', 'Assistant Manager', 2),
('Kevin Moore', 'Teller', 2),
('Rachel Taylor', 'Teller', 2),
('Jason Anderson', 'Loan Officer', 2),
('Nicole Thomas', 'Customer Support', 2),
('Brian Jackson', 'Security Officer', 2),
('Stephanie White', 'Accountant', 2),
('Andrew Harris', 'IT Support', 2),
('Jennifer Martin', 'Financial Advisor', 2),
('Matthew Thompson', 'Manager', 3),
('Lisa Garcia', 'Assistant Manager', 3),
('Ryan Martinez', 'Teller', 3),
('Ashley Robinson', 'Teller', 3),
('Joshua Clark', 'Loan Officer', 3),
('Samantha Rodriguez', 'Customer Support', 3),
('Brandon Lewis', 'Security Officer', 3),
('Megan Walker', 'Accountant', 3),
('Tyler Hall', 'IT Support', 3),
('Kimberly Allen', 'Financial Advisor', 3),
('Jonathan Young', 'Manager', 4),
('Elizabeth Hernandez', 'Assistant Manager', 4),
('Nicholas King', 'Teller', 4),
('Melissa Wright', 'Teller', 4),
('Jacob Lopez', 'Loan Officer', 4),
('Brittany Hill', 'Customer Support', 4),
('Eric Scott', 'Security Officer', 4),
('Heather Green', 'Accountant', 4),
('Adam Adams', 'IT Support', 4),
('Christina Baker', 'Financial Advisor', 4),
('Justin Nelson', 'Manager', 5),
('Rebecca Carter', 'Assistant Manager', 5),
('Benjamin Mitchell', 'Teller', 5),
('Amber Perez', 'Teller', 5),
('Aaron Roberts', 'Loan Officer', 5),
('Danielle Turner', 'Customer Support', 5),
('Jeremy Phillips', 'Security Officer', 5),
('Courtney Campbell', 'Accountant', 5),
('Kyle Parker', 'IT Support', 5),
('Victoria Evans', 'Financial Advisor', 5),
('Nathan Edwards', 'Teller', 1),
('Hannah Collins', 'Teller', 1),
('Austin Stewart', 'Customer Support', 1),
('Grace Sanchez', 'Customer Support', 1),
('Ethan Morris', 'Teller', 2),
('Olivia Rogers', 'Teller', 2),
('Zachary Reed', 'Customer Support', 2),
('Sophia Cook', 'Customer Support', 2),
('Alexander Morgan', 'Teller', 3),
('Madison Bell', 'Teller', 3),
('William Murphy', 'Customer Support', 3),
('Alexis Bailey', 'Customer Support', 3),
('Connor Rivera', 'Teller', 4),
('Natalie Cooper', 'Teller', 4),
('Luke Richardson', 'Customer Support', 4),
('Kayla Cox', 'Customer Support', 4),
('Isaiah Howard', 'Teller', 5),
('Taylor Ward', 'Teller', 5),
('Gabriel Torres', 'Customer Support', 5),
('Abigail Peterson', 'Customer Support', 5),
('Sean Gray', 'Loan Officer', 1),
('Julia Ramirez', 'Loan Officer', 2),
('Cameron James', 'Loan Officer', 3),
('Morgan Watson', 'Loan Officer', 4),
('Jordan Brooks', 'Loan Officer', 5),
('Haley Kelly', 'Financial Advisor', 1),
('Caleb Sanders', 'Financial Advisor', 2),
('Paige Price', 'Financial Advisor', 3),
('Dylan Bennett', 'Financial Advisor', 4),
('Destiny Wood', 'Financial Advisor', 5),
('Hunter Barnes', 'Security Officer', 1),
('Mackenzie Ross', 'Security Officer', 2),
('Cole Henderson', 'Security Officer', 3),
('Sierra Coleman', 'Security Officer', 4),
('Jaden Jenkins', 'Security Officer', 5),
('Brooke Perry', 'Accountant', 1),
('Tristan Powell', 'Accountant', 2),
('Mariah Long', 'Accountant', 3),
('Garrett Patterson', 'Accountant', 4),
('Ruby Hughes', 'Accountant', 5),
('Devin Flores', 'IT Support', 1),
('Chloe Washington', 'IT Support', 2),
('Blake Butler', 'IT Support', 3),
('Jasmine Simmons', 'IT Support', 4),
('Tanner Foster', 'IT Support', 5),
('Sydney Gonzales', 'HR Manager', 2),
('Parker Bryant', 'HR Manager', 3),
('Kennedy Russell', 'HR Manager', 4),
('Chase Griffin', 'HR Manager', 5);